### ISSUE TITLE
Error message when submitting a module response which related course is inactive

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Apps/fieloelr#229]
Steps to reproduce:
- The course was inactivated. 
- The module was inactivated (it had already a module response)
- The module was reactivated.
- The module response was submitted (the course was still inactive)
![image](https://user-images.githubusercontent.com/26011197/27436073-766bf6d0-5734-11e7-811f-af6aa01f5db1.png)

**Comment by apolo88** [comment]
added validation rule in module response to check in creation and submittion to have related module and course active.
