### ISSUE TITLE
Edit Answer option - wrong validation

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Apps/fieloelr#232]
Steps to reproduce:
- Go to Edit page of a question from type Single Choice
- Change the IsCorrect from one answer option to another existing one
- Press the Save button
The question is saved
- Go again to Edit page of a question from type Single Choice
- Set the IsCorrect field to false to all answer options
- Press the New button
- Fill in the answer option text field
- Set its IsCorrect field to true
- Press the Save button
The system shows the validation message below:
![image](https://user-images.githubusercontent.com/26011197/27438809-c1c9a052-573c-11e7-9687-6b95e6ad01d4.png)

**Comment by apolo88** [comment]
fixed.
