### ISSUE TITLE
Active module was deleted when Course was in status Active

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Apps/fieloelr#249]
Active modules should be deleted only if they have no related module responses and if the course is Inactive.
It was possible to delete an active module with no related module responses, but having the related course in status Active.

**Comment by apolo88** [comment]
validation added

**Comment by mfernandagf** [comment]
![image](https://user-images.githubusercontent.com/26011197/29093762-57f7358c-7c61-11e7-8872-c624864da222.png)
