### ISSUE TITLE
Create Question - it was possible to create a question with no question text

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Apps/fieloelr#252]
Different from the backend page, in classic view, it was possible to create a question with no question text.
![image](https://user-images.githubusercontent.com/26011197/27912926-de4efd50-6234-11e7-99d9-5ff2876105e2.png)

**Comment by apolo88** [comment]
updated validation rule

**Comment by mfernandagf** [comment]
Question text cannot be null neither on creation nor on edition:
![image](https://user-images.githubusercontent.com/26011197/29092171-be0cdc9c-7c5b-11e7-9a51-a4283bf2d637.png)
