### ISSUE TITLE
Predecessor course completed does not make the next course to be displayed

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Apps/fieloelr#270]
Imagine we have two courses A and B and the Course A is the predecessor for Course B.
The member does not see the Course B in the list of courses if Course A is not complete. That's fine.
But, after completing the Course A, the member should have Course B in the list, so s/he could join it, but Course B is not displayed even after Course A had been completed.

**Comment by apolo88** [comment]
fixed
