### ISSUE TITLE
Question Pool negative - Error when taking the module

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Apps/fieloelr#278]
There is no validation for a negative value in the field "Question Pool". 
However, if we have a negative value in this field, the module cannot be taken.

**Comment by apolo88** [comment]
fixed, validation added when saving the module.

**Comment by mfernandagf** [comment]
Question Pool value is validated when a module is activated:
![image](https://user-images.githubusercontent.com/26011197/29091688-23252ec4-7c5a-11e7-96bd-c25f14bbf54b.png)
