### ISSUE TITLE
Page does not refresh after confirming a question deletion

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Apps/fieloelr#307]
If the module is inactive, after confirming the deletion of a question, the success message is displayed, but the page does not refresh and keeps showing the load spinner indefinitely.
If the module is active, after confirming the deletion, the validation message is displayed, but the page does not refresh and keeps showing the load spinner indefinitely.
This happens at CI org.
![image](https://user-images.githubusercontent.com/26011197/29123441-2711cda2-7cec-11e7-8613-2a0ecea65662.png)

**Comment by tibeal** [comment]
Done in **CI**.
