### ISSUE TITLE
Change validation messages for new status

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Apps/fieloelr#317]
Now that we have two more status for the courses, some messages need to be changed according to the new status. The status "active" must be replaced by "scheduled" or "completed" when courses are in these status.
![image](https://user-images.githubusercontent.com/26011197/29841703-d54edcd4-8cdc-11e7-8a1a-660b9f043bbb.png)
![image](https://user-images.githubusercontent.com/26011197/29841948-b6cdbeb4-8cdd-11e7-9438-d1178e286e54.png)
![image](https://user-images.githubusercontent.com/26011197/29841954-bb9dac1a-8cdd-11e7-872e-503364085aa9.png)

**Comment by tibeal** [comment]
Done in **CI**.

**Comment by mfernandagf** [comment]
Only the first message was fixed. The other two are still mentioning only "active" courses.

**Comment by tibeal** [comment]
Done in **CI**.
